tasks:
  - init: docker-compose pull
  - command: docker-compose up && docker ps && docker exec fiware-orion-ld curl http://localhost:1026/version


ports:
  - port: 1026
    onOpen: ignore
  - port: 1880
    onOpen: open-browser
  - port: 8081
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker
