tasks:
  - init: docker-compose pull
  - command: docker-compose up -d && docker ps && docker exec fiware-orion-ld curl http://localhost:1026/version


ports:
  - port: 1880
    onOpen: open-browser
  - port: 5000
    onOpen: ignore
  - port: 5601
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview
  - port: 9300
    onOpen: ignore
  - port: 9600
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
