tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d


ports:
  - port: 1880
    onOpen: open-browser
  - port: 11026
    onOpen: ignore
  - port: 1026
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker
