tasks:
  - name: Shift+RunStop
    before: |
      @echo off
      egrep '^(VERSION|NAME)=' /etc/os-release
    init: |
      docker-compose up -d
      gp sync-done inter
    command: |
      gp sync-await inter
      docker ps
      docker exec orion-ld curl http://localhost:1026/version

ports:
  - port: 1026
    onOpen: ignore
  - port: 1880
    onOpen: open-browser
  - port: 8081
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
