tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up -d


ports:
  - port: 1880
    onOpen: open-browser
  - port: 9200
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
