version: "3.9"

services:

  orion-ld:
    image: fiware/orion-ld
    container_name: fiware-orion-ld
    ports:
      - 1026:1026
    depends_on:
      - mongo
    command: -dbhost mongo -db orionld

  mongo:
    image: mongo
    container_name: fiware-mongo
    command: --nojournal
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  node-red:
    build: ./node-red
    image: fiware/node-red
    container_name: fiware-node-red
    ports:
      - 1880:1880
#   volumes:
#     - ./node-red/data:/data
    depends_on:
      - orion-ld
