services:
  mongo:
    image: mongo
    command: --nojournal
    volumes:
      - ./config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081

  orion:
    image: fiware/orion-ld
    ports:
      - 1026:1026
    depends_on:
      - mongo
#   command: -dbhost mongo -db orion
    command: -dbhost mongo 
  
  node-red:
    build: ./node-red
    ports:
      - 1880:1880
#   volumes:
#     - ./node-red/data:/data
    depends_on:
      - orion
